language: node_js
node_js:
     - "9"
install:
    - npm install    
before_script:
    - createdb morerecipes-test -U postgres
    - sequelize db:migrate
script: 
    - npm test
after_success:
    - npm run coverage
services:
    - postgresql         
env:
    global:
        - NODE_ENV=test
