export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const GET_ONE_USER = 'GET_ONE_USER';
export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_SIGNIN = 'USER_SIGNIN';
export const GET_TOP_RECIPES = 'GET_TOP_RECIPES';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_RECIPE_SUCCESS = 'ADD_RECIPE_SUCCESS';
export const ADD_RECIPE_FAILURE = 'ADD_RECIPE_FAILURE';
export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const GET_ONE_RECIPE = 'GET_ONE_RECIPE';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';

